In [5]:
import numpy as np
a = np.array([7,8,9,10,11])
print(f'{a}\n{"object type:":>12} {type(a)}\n{"data type:":>12} {a.dtype}\n{"shape:":>12}\
{a.shape}\n{"dimension:" :>12} {a.ndim}\n{"arary size:":>12} {a.size}')
a1 = np.array([a]);
print(a1.shape)

[ 7  8  9 10 11]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape:(5,)
  dimension: 1
 arary size: 5
(1, 5)


In [7]:
a_zeros = np.zeros((2,3))
print(a_zeros)
a_ones = np.ones((2,4))
print(a_ones)
a_full = np.full((2,5),7)
print(a_full)
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
a_ran = np.random.random((2,3,4))
print(f'{a_ran}\n{a_ran.dtype}')

[[[0.3504713  0.93930173 0.17884891 0.79361422]
  [0.6019204  0.58906672 0.91354099 0.58726184]
  [0.36865311 0.00744724 0.3404848  0.24826325]]

 [[0.66674831 0.06390485 0.58940797 0.42781017]
  [0.25381134 0.89791623 0.00859205 0.99221197]
  [0.12423708 0.23922012 0.98719366 0.05719457]]]
float64


In [19]:
g = np.arange(28)
print(f'{g}\n{type(g)}')
print(g.reshape(2,2,7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]]


In [21]:
h = np.arange(5, 21, 2)
print(h)
print(np.arange(1,21).reshape(2,10))

[ 5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [22]:
a_ss = np.linspace(0,1,11)
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(11,)
11
