In [10]:
import numpy as np
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])

print(xa.shape, xb.shape)
print(f'{xa+xb}\n{xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [4]:
xd = np.array([[1,2],[1,2]]); print(xd)
print(np.dot(xa,xd)); print(np.dot(xb,xd))

[[1 2]
 [1 2]]
[[ 3  6]
 [ 7 14]
 [11 22]]
[[ 7 14]
 [11 22]
 [15 30]]


### Broadcasting은 차원이 다른 행렬간의 연산을 가능하게 만들어주는 기능이다.

In [5]:
ya = np.arange(1,10).reshape(3,3); print(ya)
yv1 = np.ones((3,1)); print(yv1)
yb = ya + yv1; print(yb)
yv2 = np.full((1,3),2); print(yv2)
yc = ya + yv2; print(yc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.]
 [1.]
 [1.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
karray = np.arange(21).reshape(3,7); print(karray)
print(karray[0], karray[0,4])
print(karray[:2])
print(karray[:2,:3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[0 1 2 3 4 5 6] 4
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[0 1 2]
 [7 8 9]]


In [8]:
karray = np.arange(21).reshape(3,7); print(karray)
print(karray[[0,2]]) #두번째 행까지만 출력
print(karray[:,[1,5]])
print(karray[:,1:5])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]]
[[ 1  5]
 [ 8 12]
 [15 19]]
[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]]


In [11]:
karray = np.arrange(21).reshape(3,7); print(karary)
fkarray = karray.flatten()
print(fkarray, fkarray.shape)
fkarray1 = np.array(karray.flat)
print(fkarray1)
rfkarray = karray.reshape(1,21)
print(rfkarray,rfkarray.shape)
rfkarray.resize(3,7)
print(rfkarray, rfkarray.shape)

AttributeError: module 'numpy' has no attribute 'arrange'